server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: memmedov516
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: liquibase/changelog-master.yml